Update Web maps want
WebWeWant/webwewant.fyi pull request #504
Opened 2021-10-19 16:02 UTC by prushforth

Add privacy and accessibility tags.  Update description to be less lame.  cc @nchan0154 to validate  these changes, because she's co-author.

2021-10-21 03:10 UTC, Malvoz requested changes

2021-10-21 03:10 UTC, Malvoz commented on wants/61.md
>  Our goal, and the goal of the [W3C Maps4HTML Community Group](https://www.w3.org/community/maps4html/) is to establish a standard method for web developers to include interactive web maps within HTML
```suggestion
Our goal, and the goal of the [W3C Maps for HTML Community Group](https://www.w3.org/community/maps4html/) is to establish a standard method for web developers to include interactive web maps within HTML documents.
```

2021-11-10 13:34 UTC, Malvoz approved these changes

2021-11-28 02:27 UTC, Malvoz commented
@aarongustafson would you like to merge please?

2022-03-04 00:10 UTC, prushforth commented
This would be great to get merged, in light of the [survey](https://github.com/WebWeWant/webwewant.fyi/discussions/108#discussioncomment-2290506). Thanks!

2022-04-26 22:50 UTC, tantek reviewed
Most of this update looks good. Would folks be open to some grammar improvements? E.g. the sentence "Web maps are often seen as used only for store locator pages."

2022-04-27 10:33 UTC, prushforth commented
@tantek thanks, of course!  I don't know if what I did is what you had in mind, but if you can improve it, please have a shot at it.

2022-04-29 12:51 UTC, tantek approved these changes
Much better! LGTM. Thanks for this update.

2022-07-06 22:28 UTC, merged